# Generated by Django 2.2 on 2021-08-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation', models.CharField(max_length=200)),
                ('innovator', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
