# Generated by Django 2.2 on 2021-07-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone',
            field=models.IntegerField(max_length=50),
        ),
    ]
